# Generated by Django 5.1.1 on 2025-03-02 21:35

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('dob', models.DateTimeField()),
                ('student_session', models.CharField(choices=[('24-JUN', '24-JUN'), ('25-JAN', '25-JAN'), ('25-JUN', '25-JUN'), ('26-JAN', '26-JAN')], max_length=10)),
                ('religion', models.CharField(max_length=10)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to=students.models.student_image_path)),
                ('father_name', models.CharField(max_length=255)),
                ('father_occupation', models.CharField(max_length=50)),
                ('father_phone', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('mother_phone', models.CharField(max_length=15)),
                ('present_address', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
            ],
        ),
    ]
