# Generated by Django 5.1.1 on 2025-03-07 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=255, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(max_length=50, verbose_name="Father's Occupation"),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_phone',
            field=models.CharField(max_length=15, verbose_name="Father's Phone"),
        ),
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='l_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=255, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(max_length=50, verbose_name="Mother's Occupation"),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(max_length=15, verbose_name="Mother's Phone"),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_session',
            field=models.CharField(choices=[('24-JUN', '24-JUN'), ('25-JAN', '25-JAN'), ('25-JUN', '25-JUN'), ('26-JAN', '26-JAN')], default='25-JAN', max_length=10, verbose_name='Session'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
            ],
        ),
    ]
