# Generated by Django 5.1.1 on 2025-03-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_dob_alter_student_f_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_session',
            field=models.CharField(choices=[('24-JUL', '24-JUL'), ('25-JAN', '25-JAN'), ('25-JUL', '25-JUL'), ('26-JAN', '26-JAN')], default='25-JAN', max_length=10, verbose_name='Session'),
        ),
    ]
