# Generated by Django 5.1.1 on 2025-03-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_course_rename_amount_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='students.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
