# Generated by Django 5.1.1 on 2025-03-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_courses_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_phone',
            field=models.CharField(max_length=15, null=True, verbose_name="Father's Phone"),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(max_length=15, null=True, verbose_name="Mother's Phone"),
        ),
    ]
